### ISSUE TITLE
Error in export_headers.m

### ISSUE THREAD

**Issue by kentaro** [mobiruby/mobiruby-ios#1]
When I run a build for sample app, I got an Error, "Initializer element is not a compile-time constant",  in export_headers.m at:

```
static struct BridgeSupportEnumTable enums_table[] = {
```

I commented out the line below, then the app wouldn't got the error.

```
   {.name="CGFLOAT_MAX", .value=3.4028235E+38},
```

I don't know how to fix, so just reported it.
- OSX: Mountain Lion
- Xcode: Version 4.4.1 (4F1003)

**Comment by masuidrive** [comment]
Can I have full source of export_headers.m?

**Comment by kentaro** [comment]
You can see one at https://gist.github.com/3695514.

**Comment by masuidrive** [comment]
Probably I fixed it. Could you try again?
please clean project before building. [Menu]->[Project]->[Clean]

**Comment by masuidrive** [comment]
We're talking about this issue in SapporoRubykaigi.

**Comment by kentaro** [comment]
:sushi:

**Comment by masuidrive** [comment]
Fixed in offline communication
