### ISSUE TITLE
Building example project from Xcode creates Parse issue

### ISSUE THREAD

**Issue by olierxleben** [mobiruby/mobiruby-ios#23]
Building From xcode throws confusing error message in file: cfunc_rb.c (Derived Sources) 

/path/to/mobiruby-ios/bin/mrbc: Cannot open program file. (/path/to/mobiruby-ios/modules/mruby-cfunc/src/mrb/cfunc_rb.rb)
Usage: /path/to/mobiruby-ios/bin/mrbc [switches] programfile
  switches:
  -c           check syntax only
  -o<outfile>  place the output into <outfile>
  -v           print version number, then trun on verbose mode
  -B<symbol>   binary <symbol> output in C language format
  -C<func>     function <func> output in C language format
  --verbose    run at verbose mode
  --version    print the version
  --copyright  print the copyright

Xcode`s error message: "Expected identifier or ("

I followed install instructions but don`t get it to work...

**Comment by masuidrive** [comment]
Thank you for your interest to mobiruby.
Probably mruby was changed. I'll fix in this weekend.

**Comment by masuidrive** [comment]
I reproduced on my environment.

**Comment by olierxleben** [comment]
Fix helped, now working. Thank you. :+1:

**Comment by masuidrive** [comment]
modules/mruby-cfunc was empty now. it's wrong.
We should download latest files from git.

Sorry, I'm unfamiliar with git submodule.
Could you help me?

**Comment by olierxleben** [comment]
I pulled your last updates and rerun the setup.sh, my modules/mruby-cfunc folder is not empty?

**Comment by masuidrive** [comment]
Now, I mistook. could you pull again and try build on XCode?
Doen't need to run setup.sh

**Comment by olierxleben** [comment]
its running. Got some warnings, but is working fine.

**Comment by masuidrive** [comment]
I know some warnings. I'll fix later.
Thank you for your help!
