### ISSUE TITLE
Build project error

### ISSUE THREAD

**Issue by janckerchen** [mobiruby/mobiruby-ios#26]
I found this issue in sloved list, but I  got it again. 

fresh clone,  setup.sh done,  OSX 10.8.2,  XCode4.5.2
mrbc have been complied, libffi.a also compiled
There is content in mruby-cfunc modules, but modules/mruby-cfunc/src/mrb/cfunc_rb.rb is not there.

=xcode build error=

/Users/jason/dev_opensource/mobiruby-ios/bin/mrbc: Cannot open program file. (/Users/jason/dev_opensource/mobiruby-ios/modules/mruby-cfunc/src/mrb/cfunc_rb.rb)
Usage: /Users/jason/dev_opensource/mobiruby-ios/bin/mrbc [switches] programfile
  switches:
  -c           check syntax only
  -o<outfile>  place the output into <outfile>
  -v           print version number, then trun on verbose mode
  -B<symbol>   binary <symbol> output in C language format
  -C<func>     function <func> output in C language format
  --verbose    run at verbose mode
  --version    print the version
  --copyright  print the copyright

**Comment by masuidrive** [comment]
Thank you for reporting.

I'll fix it within a few days.
Now I'm changing sub modules for mruby following.

**Comment by janckerchen** [comment]
any  change?

**Comment by masuidrive** [comment]
Sorry, I understood. mobiruby was broken now.
Now mruby had big change.
I'm fixing mruby-cfunc and mruby-cocoa what's internal module for mobiruby-ios.

I'm working hard now.
please wait more time.

Thank you.

**Comment by janckerchen** [comment]
I know it's not easy,  don't feel pressure， take your step~

**Comment by janckerchen** [comment]
Clone again,  compile failed with another error.

> AR    build/host/lib/libmruby.a 
> ar: creating archive build/host/lib/libmruby.a
> /usr/bin/ranlib: file: build/host/lib/libmruby.a(re.o) has no symbols
> /usr/bin/ranlib: file: build/host/lib/libmruby.a(regcomp.o) has no symbols
> /usr/bin/ranlib: file: build/host/lib/libmruby.a(regenc.o) has no symbols
> /usr/bin/ranlib: file: build/host/lib/libmruby.a(regerror.o) has no symbols
> /usr/bin/ranlib: file: build/host/lib/libmruby.a(regexec.o) has no symbols
> /usr/bin/ranlib: file: build/host/lib/libmruby.a(regparse.o) has no symbols
> CC    src/array.c -> build/armv7/src/array.o
> In file included from src/array.c:7:
> /Users/jason/dev_opensource/mobiruby-ios/mruby/include/mruby.h:35:10: fatal error: 'stdlib.h' file not found
> #include <stdlib.h>
>          ^
> 1 error generated.
> rake aborted!
> Command Failed: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -g -O3 -Wall -Werror-implicit-function-declaration -miphoneos-version-min=5.0 -arch armv7 -isysroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform//Developer/SDKs/iPhoneOS6.1.sdk/" -D__IPHONE_OS_VERSION_MIN_REQUIRED=50100 -fmessage-length=0 -std=gnu99 -fpascal-strings -fexceptions -fasm-blocks -gdwarf-2 -fobjc-abi-version=2 -DMRB_INT64 -I"/Users/jason/dev_opensource/mobiruby-ios/mruby/include" -I"/Users/jason/dev_opensource/mobiruby-ios/vendors/libffi/include" -I"/Users/jason/dev_opensource/mobiruby-ios/mruby-cfunc/include" -I"/Users/jason/dev_opensource/mobiruby-ios/mruby-cocoa/include" -I"/Users/jason/dev_opensource/mobiruby-ios/mobiruby-common/include" -MMD -o "build/armv7/src/array.o" -c "src/array.c"]

**Comment by janckerchen** [comment]
Clone again, compile failed with another error.
![ 2013-02-02 10 12 04](https://f.cloud.github.com/assets/68181/120845/febbaa70-6d42-11e2-97d4-49da328e4547.png)

**Comment by masuidrive** [comment]
Can I have full log on below command?

`ruby build-libmruby.rb clean libmruby --verbose`

And What's version do you use XCode?
I tried on XCode 4.6 and OSX 10.8.2.

**Comment by masuidrive** [comment]
Sorry, I found problem on Xcode 4.6.
I fixed and pushed it.

If you use Xcode 4.5 or past version, please change SDK version to '6.0' on bin/build-config.sh and build-libmruby.rb.
I'll create SDK version detector.
