### ISSUE TITLE
about SDK_IOS_VERSION

### ISSUE THREAD

**Issue by i5ting** [mobiruby/mobiruby-ios#29]
default SDK_IOS_VERSION="6.1"

if anybody SDK_IOS_VERSION=6.0 this can't compile

need to modify build-config.sh

and in file build-libmruby.rb，have the same SDK_IOS_VERSION definition，this is likely to lead to ambiguity

**Comment by masuidrive** [comment]
Thank you for trying mobiruby. :-)

Current build system is temporary version.
I'll convert shell script to ruby script later.
