### ISSUE TITLE
Builds but Doesn't Deploy on Lion

### ISSUE THREAD

**Issue by ashes999** [mobiruby/mobiruby-ios#31]
I am new to iPhone development, so apologies if this is obvious and easy to fix.

I have Mac Lion (`11.4.0` according to `uname -r`) with XCode 4.6.1. When I try to `rake`, I see: `MobiRuby required Mountain Lion / Xcode 4.6 or newer version.`

This is from `os_version.rake`. I edited it to change the OSX version check to `OSX_VERSION < 11.4`.

I want to see how far it gets. What specifically from Lion do we need?

The application builds; I got some errors about `autoreconf` not found, so I ran `brew install automake`, did a clean and rake.

The build completes. I get an error on deployment:

```
[DEBUG] Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 "iOS Simulator failed to install the application." UserInfo=0x7ff728c4a7d0 {NSLocalizedDescription=iOS Simulator failed to install the application., DTiPhoneSimulatorUnderlyingErrorCodeKey=-1}
rake aborted!
Command failed with status (1): [./bin/ios-sim launch "build/Debug-iphonesi...]
tasks/simulator.rake:9:in `block in <top (required)>'
/Users/User/.rvm/gems/ruby-1.9.3-p392@global/bin/ruby_noexec_wrapper:14:in `eval'
/Users/User/.rvm/gems/ruby-1.9.3-p392@global/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => default => run
(See full trace by running task with --trace)
```

I see a blank, black iPhone emulator screen. Nothing else.

What am I doing wrong?

**Comment by masuidrive** [comment]
Sorry, I don't have Lion installed machine.
Could you try build on Xcode?

**Comment by masuidrive** [comment]
Could you pull recent source?
Last week, I removed pch files by mistake. after that I reverted it.

https://github.com/mobiruby/mobiruby-ios/blob/master/mobiruby-ios/mobiruby-ios-Prefix.pch

**Comment by ashes999** [comment]
Okay, I will pull source now and let you know. I think I did not set up Xcode correctly, so I deleted my previous comments. I am investigating now. (eg. I don't have iOS 6 simulator, but mobiruby-ios deploys by default to the iOS 6.1 simulator)

**Comment by ashes999** [comment]
It looks like `export_headers.m` is missing. I see:

```
/mobiruby-ios/bin/build-exports.rb:99 in 'initialize': No such file or directory - /mobiruby-ios/tmp/export_headers.m (Errno::ENOENT)
  from /mobiruby-ios/bin/build-exports.rb:99:in 'open'
  from /mobiruby0ios/bin/build-exports.rb:99
```

**Comment by troelskn** [comment]
I get the same error on my machine. The iPhone simulator launches, but there is a blank screen, and I get this in the terminal:

```
[DEBUG] Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 "iOS Simulator failed to install the application." UserInfo=0x7ff61bc1c420 {NSLocalizedDescription=iOS Simulator failed to install the application., DTiPhoneSimulatorUnderlyingErrorCodeKey=-1}
rake aborted!
Command failed with status (1): [./bin/ios-sim launch "build/Debug-iphonesi...]
tasks/simulator.rake:9:in `block in <top (required)>'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => default => run
(See full trace by running task with --trace)
```

**Comment by troelskn** [comment]
I tried using my system iPhone simulator instead:

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app/Contents/MacOS/iPhone\ Simulator launch "$(pwd)/build/Debug-iphonesimulator/mobiruby-ios.app"
```

The simulator launches and there is a mobiruby-app present. However, when I click on it, it just loads and the exits immediately.

**Comment by ashes999** [comment]
Sorry for the trouble. It seems to be working now. The inital rake failed (simulator session timed out), but a subsequent session completed.

I'm closing this issue. Feel free to reopen @troelskn

**Comment by troelskn** [comment]
I tried, but I just noticed that the build phase has errors. It seems that `bin/build-exports.rb` links to some very specific gem versions:

```
ENV['GEM_HOME'] = ENV['GEM_PATH'] = "/Library/Ruby/Gems/1.8"
require 'rubygems'
require 'nokogiri'

gem 'xcodeproj', '0.3.5'
require 'xcodeproj'
```

Which gives errors as my main ruby is 1.9.2 under rvm:

```
/bin/sh -c /Users/troelskn/Projects/mobiruby-ios/build/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Script-59ACFC6E15FDBA41004BE69E.sh
WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:777:in `report_activate_error': Could not find RubyGem xcodeproj (= 0.3.5) (Gem::LoadError)
  from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:211:in `activate'
  from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:1056:in `gem'
  from /Users/troelskn/Projects/mobiruby-ios/bin/build-exports.rb:8
Command /bin/sh failed with exit code 1
```

I tried to edit `bin/build-exports.rb` with:

```
ENV['GEM_HOME'] = ENV['GEM_PATH'] = "/Users/troelskn/.rvm/gems/ruby-1.9.3-p327"
require 'rubygems'
require 'nokogiri'

gem 'xcodeproj'
require 'xcodeproj'
```

But it just segfaults instead.

```
/bin/sh -c /Users/troelskn/Projects/mobiruby-ios/build/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Script-59ACFC6E15FDBA41004BE69E.sh
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/nokogiri-1.5.9/lib/nokogiri/nokogiri.bundle: [BUG] Segmentation fault
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

/Users/troelskn/Projects/mobiruby-ios/build/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Script-59ACFC6E15FDBA41004BE69E.sh: line 2: 17368 Abort trap: 6           GEM_HOME= GEM_PATH= RUBY_VERSION= $PROJECT_DIR/bin/build-exports.rb $PROJECT_DIR/tmp/export_headers.m
Command /bin/sh failed with exit code 134
```

I suspect this is the real culprit, but I just didn't notice before. Any suggestions? (Or should I open a new issue?)

**Comment by troelskn** [comment]
And a bonus information - I tried switching to system ruby (1.8.7), but no dice:

```
rake
(in /Users/troelskn/Projects/mobiruby-ios)
rake aborted!
private method `verbose' called for Rake:Module
./submodules/mruby/Rakefile:8:in `load'
(See full trace by running task with --trace)
```

**Comment by masuidrive** [comment]
@troelskn Can I have details log when it's ran on 1.8.7.

```
rake --trace
```

**Comment by troelskn** [comment]
Sure - It doesn't tell much though:

```
$ rake --trace
(in /Users/troelskn/Projects/mobiruby-ios)
rake aborted!
private method `verbose' called for Rake:Module
/Users/troelskn/Projects/mobiruby-ios/submodules/mruby/tasks/ruby_ext.rake:48
./submodules/mruby/Rakefile:8:in `load'
./submodules/mruby/Rakefile:8
./tasks/build.rake:6:in `load'
./tasks/build.rake:6
/Users/troelskn/Projects/mobiruby-ios/Rakefile:2:in `load'
/Users/troelskn/Projects/mobiruby-ios/Rakefile:2
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2383:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2383:in `raw_load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2017:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2016:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:31
```

**Comment by ashes999** [comment]
@troelskn It worked for me using Ruby 1.9.3 (installed with Homebrew), and an unmodified `build-exports.rb` file. Can you try that? Did "vanilla" Ruby work before trying to install mobiruby?

**Comment by troelskn** [comment]
I think it works as it should. But is mobiruby at all tested on 1.8.7?

**Comment by masuidrive** [comment]
@troelskn Can I have your rake version? `rake --version`

Probably the problem depends on Rake version.
I fixed it on mruby and sent pull request.
I'm waiting to merge it.

**Comment by troelskn** [comment]
Ah .. Indeed:

```
rvm use default
Using /Users/troelskn/.rvm/gems/ruby-1.9.3-p327
$ rake --version
rake, version 10.0.3
$ rvm use system
Now using system ruby.
$ rake --version
rake, version 0.8.7
```

So that explains some. I'll try updating my 1.8 gemset and see what happens - might take a while. Though, even if this resolves the issue, it's still a problem since it means that the build process somehow circumvents rvm and use the system ruby/gems even when set to use 1.9.3

**Comment by troelskn** [comment]
OK. It now builds and run as it should. I would prefer to be able to use ruby 1.9.3 via rvm though.

**Comment by troelskn** [comment]
Curiously, if I switch back to ruby 1.9.3, I can still launch the app. I tried to go to the "editor" screen and execute `puts RUBY_VERSION`, but it just crashes.

**Comment by masuidrive** [comment]
mruby don't have RUBY_VERSION and "Editor" screen don't catch exception yet.
