### ISSUE TITLE
Sounds from sample game don't play

### ISSUE THREAD

**Issue by ashes999** [mobiruby/mobiruby-ios#34]
Hi,

Neither of the sample sounds (`bgm_00.aif` or `tap_se_00.wav`) seem to be playing for me. The creation of `AudioPlayer` is fine, and setting loops and volume is okay, but nothing plays.

Is this a known bug, or is it my setup?

**Comment by masuidrive** [comment]
I heard bgm on iOS device. but tap_se doesn't play. 
I'll fix it.

**Comment by masuidrive** [comment]
I fixed on HEAD. Could you try it?
I can play BGM and sounds on Simulator and iPhone5.

**Comment by ashes999** [comment]
It looks like it's working now in the simulator with .wav files. The BGM is also playing (.AIF file). 

Thanks!
