### ISSUE TITLE
Error when installing nokogiri

### ISSUE THREAD

**Issue by oeil2lynx** [mobiruby/mobiruby-ios#40]
Hi, 

I've got an error when I run the command "GEM_HOME=/Library/Ruby/Gems/1.8 GEM_PATH=/Library/Ruby/Gems/1.8 sudo /usr/bin/gem install nokogiri rake"

ERROR:  Error installing nokogiri:
    nokogiri requires Ruby version >= 1.9.2.

I'm trying to install mobiruby on Lion

**Comment by masuidrive** [comment]
Sorry, MobiRuby supported from Mtn Lion.
Could you update to Mtn Lion or newer?
I will support Mavericks in this weekend.

**Comment by oeil2lynx** [comment]
Thanks a lot for your response but I cannot upgrade to Mtn Lion because of tools I need for my work.
I'm not sure it will still work after upgrading.
I ll try later.
Best regards and thanks again.
