### ISSUE TITLE
Game not work in iOS simulator in XCode

### ISSUE THREAD

**Issue by OpakAlex** [mobiruby/mobiruby-ios#9]
When I compile game app it dosent work, show image mobyruby on then I see black screen.

2012-09-13 10:34:03.923 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AudioIPCDriver.kext/Contents/Resources/AudioIPCPlugIn.bundle/Contents/MacOS/AudioIPCPlugIn:  dlopen(/System/Library/Extensions/AudioIPCDriver.kext/Contents/Resources/AudioIPCPlugIn.bundle/Contents/MacOS/AudioIPCPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:03.929 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AudioIPCDriver.kext/Contents/Resources/AudioIPCPlugIn.bundle/Contents/MacOS/AudioIPCPlugIn:  dlopen(/System/Library/Extensions/AudioIPCDriver.kext/Contents/Resources/AudioIPCPlugIn.bundle/Contents/MacOS/AudioIPCPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:03.949 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn:  dlopen(/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:03.954 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn:  dlopen(/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:03.984 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn:  dlopen(/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:03.988 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn:  dlopen(/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:04.042 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn:  dlopen(/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
2012-09-13 10:34:04.068 mobiruby-ios[16451:12003] Error loading /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn:  dlopen(/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn, 262): Symbol not found: ___CFObjCIsCollectable
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /System/Library/Frameworks/Security.framework/Versions/A/Security

TypeError: Cannot convert to c value

**Comment by masuidrive** [comment]
I fixed sample apps. Could you try again?

**Comment by OpakAlex** [comment]
i have some errors when compile app now
/var/www/moby_ruby/mobiruby-ios/export_headers.m:1147:78: warning: 'NSFileHandleNotificationMonitorModes' is deprecated [-Wdeprecated-declarations]
    {.name="NSFileHandleNotificationMonitorModes", .type="@", .value=(void*)&NSFileHandleNotificationMonitorModes},
                                                                             ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2494:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[0].value = mrb_fixnum_value(1);

**Comment by masuidrive** [comment]
Thank you for reply. Could you [Project]->[Clean] and build again?
So If you get same error, Could you put export_headers.m to gist?

**Comment by OpakAlex** [comment]
When I pull from git, I do  [Project]->[Clean] and build. But I have some errors.

This my export_headers.m
https://gist.github.com/3769669

this my errors

CompileC /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Objects-normal/i386/export_headers.o export_headers.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/www/moby_ruby/mobiruby-ios
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -std=gnu99 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-sign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk -fexceptions -fasm-blocks -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.6 -g -Wno-conversion -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -D__IPHONE_OS_VERSION_MIN_REQUIRED=50100 -iquote /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/mobiruby-ios-generated-files.hmap -I/Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/mobiruby-ios-own-target-headers.hmap -I/Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/mobiruby-ios-all-target-headers.hmap -iquote /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/mobiruby-ios-project-headers.hmap -I/Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Products/Debug-iphonesimulator/include -I/Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/DerivedSources/i386 -I/Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/DerivedSources -F/Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Products/Debug-iphonesimulator -I/var/www/moby_ruby/mobiruby-ios/modules/mruby/include -I/var/www/moby_ruby/mobiruby-ios/modules/libffi/include -I/var/www/moby_ruby/mobiruby-ios/modules/mobiruby-common/include -I/var/www/moby_ruby/mobiruby-ios/modules/mruby-cocoa/include -I/var/www/moby_ruby/mobiruby-ios/modules/mruby-cfunc/include -DALLOC_PADDING=8 -DUSE_MRBC_DATA -include /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/PrecompiledHeaders/mobiruby-ios-Prefix-ffchzsohmdtvxlcvipubagbqxpez/mobiruby-ios-Prefix.pch -MMD -MT dependencies -MF /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Objects-normal/i386/export_headers.d --serialize-diagnostics /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Objects-normal/i386/export_headers.dia -c /var/www/moby_ruby/mobiruby-ios/export_headers.m -o /Users/alexopak/Library/Developer/Xcode/DerivedData/mobiruby-ios-cbssgrcvhxigrhczyoyzxfsmdkdn/Build/Intermediates/mobiruby-ios.build/Debug-iphonesimulator/mobiruby-ios.build/Objects-normal/i386/export_headers.o

/var/www/moby_ruby/mobiruby-ios/export_headers.m:387:69: warning: 'UIKeyboardBoundsUserInfoKey' is deprecated [-Wdeprecated-declarations]
    {.name="UIKeyboardBoundsUserInfoKey", .type="@", .value=(void_)&UIKeyboardBoundsUserInfoKey},
                                                                    ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:499:64: warning: 'UINibProxiedObjectsKey' is deprecated [-Wdeprecated-declarations]
    {.name="UINibProxiedObjectsKey", .type="@", .value=(void_)&UINibProxiedObjectsKey},
                                                               ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:503:72: warning: 'UIKeyboardCenterEndUserInfoKey' is deprecated [-Wdeprecated-declarations]
    {.name="UIKeyboardCenterEndUserInfoKey", .type="@", .value=(void_)&UIKeyboardCenterEndUserInfoKey},
                                                                       ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:778:68: warning: 'NSErrorFailingURLStringKey' is deprecated [-Wdeprecated-declarations]
    {.name="NSErrorFailingURLStringKey", .type="@", .value=(void_)&NSErrorFailingURLStringKey},
                                                                   ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:786:74: warning: 'UIKeyboardCenterBeginUserInfoKey' is deprecated [-Wdeprecated-declarations]
    {.name="UIKeyboardCenterBeginUserInfoKey", .type="@", .value=(void_)&UIKeyboardCenterBeginUserInfoKey},
                                                                         ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:978:59: warning: 'kCAFillModeFrozen' is deprecated [-Wdeprecated-declarations]
    {.name="kCAFillModeFrozen", .type="@", .value=(void_)&kCAFillModeFrozen},
                                                          ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:1147:78: warning: 'NSFileHandleNotificationMonitorModes' is deprecated [-Wdeprecated-declarations]
    {.name="NSFileHandleNotificationMonitorModes", .type="@", .value=(void*)&NSFileHandleNotificationMonitorModes},
                                                                             ^
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2494:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[0].value = mrb_fixnum_value(1);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2495:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[1].value = mrb_fixnum_value(4);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2496:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[2].value = mrb_fixnum_value(1);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2497:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[3].value = mrb_fixnum_value(2);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2498:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[4].value = mrb_fixnum_value(8);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2499:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[5].value = mrb_fixnum_value(5);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2500:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[6].value = mrb_fixnum_value(3);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2501:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[7].value = mrb_fixnum_value(2);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2502:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[8].value = mrb_fixnum_value(4);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2503:26: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[9].value = mrb_fixnum_value(0);
                         ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2504:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[10].value = mrb_fixnum_value(1);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2505:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[11].value = mrb_fixnum_value(2);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2506:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[12].value = mrb_fixnum_value(1);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2507:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[13].value = mrb_fixnum_value(0);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2508:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[14].value = mrb_fixnum_value(4);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2509:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[15].value = mrb_fixnum_value(2);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2510:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[16].value = mrb_fixnum_value(3);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2511:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[17].value = mrb_fixnum_value(1);
                          ^ ~~~~~~~~~~~~~~~~~~~
/var/www/moby_ruby/mobiruby-ios/export_headers.m:2512:27: error: assigning to 'int' from incompatible type 'mrb_value' (aka 'struct mrb_value'); 
    enums_table[18].value = mrb_fixnum_value(0);
                          ^ ~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7 warnings and 20 errors generated.

**Comment by masuidrive** [comment]
Did you pull submodules?

**Comment by OpakAlex** [comment]
Yes

**Comment by masuidrive** [comment]
Could you see modules/mruby-cocoa/include/cocoa.h line 51?
Is it same as below URL's line?
https://github.com/mobiruby/mruby-cocoa/blob/2ff6b45e89651a5b61f5520f7360763fc9d6fad2/include/cocoa.h#L51

If it's "int value", it's old version.

**Comment by OpakAlex** [comment]
sorry, I start new folder with your project, but when run game, i see black screen, and this errors
TypeError: Cannot convert to c value
TypeError: Cannot convert to c value
TypeError: Cannot convert to c value
TypeError: Cannot convert to c value
TypeError: Cannot convert to c value
TypeError: Cannot convert to c value

=(

**Comment by masuidrive** [comment]
What's version your Xcode and OSX?

**Comment by OpakAlex** [comment]
Version 4.3.3 (4E3002) Xcode

Lion OS version 10.7.4

**Comment by masuidrive** [comment]
Could you update Xcode 4.4 or latest version?

**Comment by OpakAlex** [comment]
Yes, but i will do this in the evening.

**Comment by masuidrive** [comment]
Thank you :-)

**Comment by masuidrive** [comment]
Sorry, I mistook latest git submodule commands.
Could you re-clone from https://github.com/mobiruby/mobiruby-ios.git ?

**Comment by OpakAlex** [comment]
Yes, I clone, when compile i have this new error:

#ifdef **arm**
  #include <arm/arch.h>
  #ifdef _ARM_ARCH_7S
    #include "include/armv7s/ffi.h"
  #elif _ARM_ARCH_7
    #include "include/armv7/ffi.h"
  #endif
#elif defined(__i386__)
  #include "include/i386/ffi.h"
#endif

#include "include/i386/ffi.h" file not found =)

**Comment by masuidrive** [comment]
What's version of Xcode?
If you install Xcode to /Applications, please set Xcode path to  xcode-select.

ex) sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

**Comment by OpakAlex** [comment]
I install Version 4.5 (4G182), then
do sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
but get error #include "include/i386/ffi.h" file not found

**Comment by masuidrive** [comment]
Could you ./setup.sh again?
Thank you for your help!

**Comment by OpakAlex** [comment]
Yo!
we fix compile error, but error in game still:
TypeError: CFunc::Struct cannot convert to C value
TypeError: CFunc::Struct cannot convert to C value
TypeError: CFunc::Struct cannot convert to C value
TypeError: CFunc::Struct cannot convert to C value
TypeError: CFunc::Struct cannot convert to C value
TypeError: CFunc::Struct cannot convert to C value

**Comment by masuidrive** [comment]
Thank you!
I'll check CFunc::Struct code.

**Comment by OpakAlex** [comment]
I'll wait impatiently fixing this error.
Thank you!

**Comment by masuidrive** [comment]
Could you git pull, Project->Clean and Run again?

**Comment by OpakAlex** [comment]
It's work!!!
Thank you!
Thank you!
Thank you!

**Comment by masuidrive** [comment]
Thank you for your big help!!
Arigato! :sushi:
